spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/my_project_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    #username: user
    #password: 1234
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  mail:
    host: smtp.gmail.com         # âœ… Gmail SMTP ì„œë²„ ì£¼ì†Œ (ê³ ì •)
    port: 587                    # âœ… TLS/STARTTLSë¥¼ ìœ„í•œ í¬íŠ¸ (ê³ ì •)
    username: dlaqudtn107@gmail.com    # ğŸ‘ˆ ì´ë©”ì¼ ì¸ì¦ ì½”ë“œë¥¼ ë³´ë‚¼ ë°œì‹ ì Gmail ì£¼ì†Œ
    password: kybpyshvnghaycpo # ğŸ‘ˆ 16ìë¦¬ ì•± ë¹„ë°€ë²ˆí˜¸ë¥¼ ì—¬ê¸°ì— ì…ë ¥
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true         # ë³´ì•ˆ í†µì‹  í™œì„±í™” (ê¶Œì¥)
          timeout: 5000          # íƒ€ì„ì•„ì›ƒ ì„¤ì • (ì„ íƒ ì‚¬í•­)
  data:
    redis:
      host: localhost # Dockerë¡œ ë„ì› ìœ¼ë¯€ë¡œ localhost
      port: 6379      # Dockerì˜ 6379 í¬íŠ¸ì™€ ì—°ê²°ë¨

  jpa:
    hibernate:
      ddl-auto: update